SUBSAMPLE_SEED_VALUE = 42
SUBSAMPLE_SAMPLE_SIZE = 5000

GENERAL_SUBSET_ANALYSIS_START = 1800
GENERAL_SUBSET_ANALYSIS_END = 1970
GENERAL_SUBSET_STEP_SIZE = 10

RESTRICTED_SUBSET_ANALYSIS_START = 1935
RESTRICTED_SUBSET_ANALYSIS_END = 1945
RESTRICTED_SUBSET_STEP_SIZE = 1

TIME_EFFICIENCY_SAMPLE_SIZE = 500
